<?php
declare(strict_types=1);
$name = trim((string)$profile['display_name']);
$entriesByType = [];
foreach ($profile['entries'] as $entry) $entriesByType[$entry['entry_type']][] = $entry;
$listUrl = jyp_path_url('/' . $base . '/');
?>
<div class="jyp-profile" data-jyp-profile>
  <nav class="jyp-profile__crumb" aria-label="<?=jyp_h(jyp_t('Breadcrumb'))?>"><a href="<?=jyp_h($listUrl)?>"><?=jyp_h(jyp_t('People'))?></a><span aria-hidden="true">/</span><span><?=jyp_h($name)?></span></nav>
  <header class="jyp-profile__hero">
    <div class="jyp-profile__portrait"><?php if ($profile['photo_url']): ?><img src="<?=jyp_h($profile['photo_url'])?>" alt="<?=jyp_h($name)?>"><?php else: ?><span aria-hidden="true"><?=jyp_h(mb_strtoupper(mb_substr($name,0,1,'UTF-8'),'UTF-8'))?></span><?php endif; ?></div>
    <div class="jyp-profile__identity"><p class="jyp-eyebrow"><?=jyp_h($profile['organization_unit'] ?: jyp_t('Professional profile'))?></p><h1><?=jyp_h($name)?></h1><?php if ($profile['credentials']): ?><p class="jyp-profile__credentials"><?=jyp_h($profile['credentials'])?></p><?php endif; ?><?php if ($profile['position_title']): ?><h2><?=jyp_h($profile['position_title'])?></h2><?php endif; ?><?php if ($profile['headline']): ?><p class="jyp-profile__headline"><?=jyp_h($profile['headline'])?></p><?php endif; ?><div class="jyp-profile__badges"><?php foreach ($profile['terms'] as $term): ?><span><?=jyp_h($term['name'])?></span><?php endforeach; ?></div></div>
    <aside class="jyp-profile__quick"><p><?=jyp_h(jyp_t('Connect'))?></p><?php if ($profile['public_email']): ?><a href="mailto:<?=jyp_h($profile['public_email'])?>"><?=jyp_h(jyp_t('Email'))?></a><?php endif; ?><?php foreach ($profile['links'] as $link): ?><a href="<?=jyp_h($link['url'])?>" target="_blank" rel="noopener noreferrer"><?=jyp_h($link['label'])?></a><?php endforeach; ?><button type="button" data-jyp-share data-share-label="<?=jyp_h(jyp_t('Share'))?>" data-copied-label="<?=jyp_h(jyp_t('Link copied'))?>" data-copy-error-label="<?=jyp_h(jyp_t('Unable to copy the link.'))?>" hidden><?=jyp_h(jyp_t('Share'))?></button><span class="jyp-sr-only" data-jyp-share-status aria-live="polite"></span></aside>
  </header>
  <nav class="jyp-tabs" aria-label="<?=jyp_h(jyp_t('Profile sections'))?>"><a id="jyp-tab-overview" href="#overview"><?=jyp_h(jyp_t('Overview'))?></a><?php foreach ($entryTypes as $type => $definition): if (empty($entriesByType[$type])) continue; ?><a id="jyp-tab-<?=jyp_h($type)?>" href="#<?=jyp_h($type)?>"><?=jyp_h(jyp_t($definition['label']))?></a><?php endforeach; ?></nav>
  <section class="jyp-panel" id="overview" data-jyp-panel><div class="jyp-panel__head"><p><?=jyp_h(jyp_t('Profile'))?></p><h2><?=jyp_h(jyp_t('About %s', $name))?></h2></div><div class="jyp-biography"><?=nl2br(jyp_h($profile['biography'] ?: jyp_t('Biography information will be available soon.')))?></div><?php if ($profile['staff_identifier']): ?><dl class="jyp-facts"><div><dt><?=jyp_h(jyp_t('Public identifier'))?></dt><dd><?=jyp_h($profile['staff_identifier'])?></dd></div></dl><?php endif; ?></section>
  <?php foreach ($entryTypes as $type => $definition): $entries=$entriesByType[$type]??[]; if ($entries===[]) continue; ?>
    <?php $typeYears=[]; foreach($entries as $entry) if(!empty($entry['year'])) $typeYears[(int)$entry['year']]=true; krsort($typeYears); ?><section class="jyp-panel" id="<?=jyp_h($type)?>" data-jyp-panel data-layout="<?=jyp_h($definition['layout'])?>"><div class="jyp-panel__head"><div><p><?=jyp_h(jyp_t('Professional record'))?></p><h2><?=jyp_h(jyp_t($definition['label']))?></h2></div><?php if ($typeYears !== []): ?><label hidden data-jyp-enhancement><span><?=jyp_h(jyp_t('Filter by year'))?></span><select data-jyp-year><option value=""><?=jyp_h(jyp_t('All years'))?></option><?php foreach (array_keys($typeYears) as $year): ?><option value="<?=$year?>"><?=$year?></option><?php endforeach; ?></select></label><?php endif; ?></div><div class="jyp-entry-list"><?php foreach ($entries as $entry): ?><article class="jyp-entry" data-year="<?=!empty($entry['year'])?(int)$entry['year']:''?>"><?php if ($entry['year']): ?><time><?=(int)$entry['year']?></time><?php endif; ?><div><h3><?php if ($entry['external_url']): ?><a href="<?=jyp_h($entry['external_url'])?>" target="_blank" rel="noopener noreferrer"><?=jyp_h($entry['title'])?></a><?php else: ?><?=jyp_h($entry['title'])?><?php endif; ?></h3><?php if ($entry['summary']): ?><p><?=nl2br(jyp_h($entry['summary']))?></p><?php endif; ?></div></article><?php endforeach; ?></div><p class="jyp-empty-year" data-jyp-empty-year hidden aria-live="polite"><?=jyp_h(jyp_t('No records match this year.'))?></p></section>
  <?php endforeach; ?>
</div>
